### ISSUE TITLE
Send Email AWS SDK for JavaScript is not working

### ISSUE THREAD

**Issue by KirankBadiger** [awsdocs/aws-sdk-for-javascript-v3#38] opened 2021-03-23 07:24 UTC
`_const AWS = require('aws-sdk');
AWS.config.update({region:'ap-south-1'});
var ses = new AWS.SES();

var sesParams = {
    Destination: {
     ToAddresses: [
        "**@gmail.com"
     ]
    }, 
    Message: {
     Body: {
      Html: {
       Charset: "UTF-8", 
       Data: "This message body contains HTML formatting."
      }, 
      Text: {
       Charset: "UTF-8", 
       Data: "some data"
      }
     }, 
     Subject: {
      Charset: "UTF-8", 
      Data: "Order Status"
     }
    }, 
    ReplyToAddresses: [
    ], 
    ReturnPath: "", 
    ReturnPathArn: "",
    Source: "******@gmail.com",
    SourceArn: "",
   };
   var sendPromise = ses.sendEmail(sesParams).promise();

// Handle promise's fulfilled/rejected states
sendPromise.then(
  function(data) {
    console.log(data.MessageId);
  }).catch(
    function(err) {
    console.error(err, err.stack);
  });_`

**Followed all the instruction as per the documentation**
[https://docs.amazonaws.cn/en_us/sdk-for-javascript/v2/developer-guide/ses-examples-sending-email.html#ses-examples-sendma](url)

**Error:**

PS F:\Projects\AWS SDK Projects> node .\sendMail.js
InvalidParameterValue: Invalid email address .
    at Request.extractError (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\protocol\query.js:50:29)
    at Request.callListeners (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'InvalidParameterValue',
  time: 2021-03-22T21:12:55.853Z,
  requestId: '97744c92-8e0f-4c54-bfdc-32c0d9d9210c',
  statusCode: 400,
  retryable: false,
  retryDelay: 76.12391045843472
} InvalidParameterValue: Invalid email address .
    at Request.callListeners (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (F:\Projects\AWS SDK Projects\node_modules\aws-sdk\lib\sequential_executor.js:116:18)

**Comment by brmur** [comment] 2021-04-28 14:14
Duplicate of https://github.com/awsdocs/aws-doc-sdk-examples/issues/1725

**Closed by brmur** 2021-04-28 14:14 UTC
